"""initial

Revision ID: 91838bac70a5
Revises: 
Create Date: 2026-07-06 21:35:31.701828
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '91838bac70a5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply forward migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
